#!/usr/bin/env python3
"""
Correction Classifier for Claude Code Session Transcripts
==========================================================

Classifies user-role messages in JSONL session files into categories:
  - human_correction: A real human correcting the agent's behavior
  - human_directive: A new instruction or task from a human
  - human_approval: Human approving or accepting agent output
  - human_question: Human asking a question
  - system_message: Tool results, system notifications, hook output, slash commands
  - other: Everything else (empty messages, unclear content)

Uses multi-signal classification:
  1. Structural signals (tool_result blocks, tool_use_id, sourceToolAssistantUUID)
  2. XML/tag patterns (system-reminder, command-name, local-command-*)
  3. Lexical patterns (correction language, question marks, approval words)
  4. Message length distribution
  5. Position in conversation (first message = likely directive)
"""

import json
import re
import sys
import os
import random
from dataclasses import dataclass, field, asdict
from typing import Optional
from pathlib import Path


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class ClassifiedMessage:
    """A single classified message from a session transcript."""
    session_id: str
    session_type: str          # "interactive" or "subagent"
    message_index: int         # 0-based index among user messages in session
    line_index: int            # 0-based line number in JSONL file
    raw_text: str              # Extracted text content
    label: str                 # Classification label
    confidence: float          # 0.0 - 1.0
    signals: dict              # Signals that contributed to classification
    prev_assistant_text: str = ""   # Previous assistant message text (context)
    next_assistant_text: str = ""   # Next assistant message text (context)

    def to_dict(self):
        return asdict(self)


# ---------------------------------------------------------------------------
# Text extraction helpers
# ---------------------------------------------------------------------------

def extract_text_from_content(content) -> str:
    """Extract human-readable text from message content field."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, dict):
                if block.get("type") == "text":
                    parts.append(block.get("text", ""))
                elif block.get("type") == "tool_result":
                    inner = block.get("content", "")
                    if isinstance(inner, str):
                        parts.append(inner)
                    elif isinstance(inner, list):
                        for sub in inner:
                            if isinstance(sub, dict) and sub.get("type") == "text":
                                parts.append(sub.get("text", ""))
        return "\n".join(parts)
    return ""


def extract_assistant_text(content) -> str:
    """Extract text from assistant message content (ignoring thinking/toolCall blocks)."""
    if isinstance(content, str):
        return content[:500]
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                parts.append(block.get("text", ""))
        return "\n".join(parts)[:500]
    return ""


# ---------------------------------------------------------------------------
# Structural signal detection
# ---------------------------------------------------------------------------

def has_tool_result_blocks(content) -> bool:
    """Check if content contains tool_result blocks (strongest signal for system_message)."""
    if isinstance(content, list):
        for block in content:
            if isinstance(block, dict) and block.get("type") == "tool_result":
                return True
    return False


def has_tool_use_id(content) -> bool:
    """Check if any content block has a tool_use_id field."""
    if isinstance(content, list):
        for block in content:
            if isinstance(block, dict) and "tool_use_id" in block:
                return True
    return False


def is_old_format_tool_result(obj) -> bool:
    """Check if this is an old-format toolResult message (type=message, role=toolResult)."""
    if obj.get("type") == "message":
        return obj.get("message", {}).get("role") == "toolResult"
    return False


def has_source_tool_uuid(obj) -> bool:
    """Check if this message was generated by a tool (subagent tool result return)."""
    return obj.get("sourceToolAssistantUUID") is not None


# ---------------------------------------------------------------------------
# Tag/pattern signal detection
# ---------------------------------------------------------------------------

SYSTEM_TAG_PATTERNS = [
    re.compile(r"<system-reminder>", re.IGNORECASE),
    re.compile(r"<command-name>", re.IGNORECASE),
    re.compile(r"<local-command-caveat>", re.IGNORECASE),
    re.compile(r"<local-command-stdout>", re.IGNORECASE),
    re.compile(r"<local-command-stderr>", re.IGNORECASE),
    re.compile(r"<environment_details>", re.IGNORECASE),
    re.compile(r"<task_action_results>", re.IGNORECASE),
    re.compile(r"<automated-reminder>", re.IGNORECASE),
    re.compile(r"<task-notification>", re.IGNORECASE),
    re.compile(r"<run_context>", re.IGNORECASE),
]

SYSTEM_PREFIX_PATTERNS = [
    re.compile(r"^\s*\[Request interrupted", re.IGNORECASE),
    re.compile(r"^\s*\[Image:", re.IGNORECASE),
    re.compile(r"^\s*Stop hook feedback:", re.IGNORECASE),
    re.compile(r"^\s*NOTE:\s+/\w+", re.IGNORECASE),  # Deprecation notices from hooks
]

# Slash command injection pattern: content starts with # and looks like a command template
SLASH_COMMAND_PATTERN = re.compile(
    r"^\s*#\s+(?:Ralph Loop|Create a plan|Deepen Plan|Work Plan|Review|"
    r"Compound Engineer|Agent|Code Review|Plan Execution|Execute)",
    re.IGNORECASE
)

# Markdown heading that looks like an injected prompt/template (not a human message)
INJECTED_PROMPT_PATTERN = re.compile(
    r"^\s*#\s+\S.{10,}\n\n##\s+", re.MULTILINE
)

# Agent loop / orchestrator prompt patterns
AGENT_LOOP_PATTERNS = [
    re.compile(r"^\s*You are \w+, an autonomous agent", re.IGNORECASE),
    re.compile(r"^\s*##\s*SECURITY NOTICE", re.IGNORECASE),
    re.compile(r"^\s*This session is being continued from a previous conversation", re.IGNORECASE),
    re.compile(r"^\s*Conversation info \(untrusted metadata\):", re.IGNORECASE),
    re.compile(r"^\s*\[Queued messages while agent was busy\]", re.IGNORECASE),
]

# Maximum text length for correction classification -- beyond this, the message
# is almost certainly a system prompt, agent loop injection, or long directive,
# not a short human correction. Real corrections are conversational and brief.
MAX_CORRECTION_TEXT_LENGTH = 1000


def has_system_tags(text: str) -> bool:
    """Check if text contains system-generated XML tags."""
    for pat in SYSTEM_TAG_PATTERNS:
        if pat.search(text):
            return True
    return False


def has_system_prefix(text: str) -> bool:
    """Check if text starts with a system-generated prefix."""
    for pat in SYSTEM_PREFIX_PATTERNS:
        if pat.search(text):
            return True
    return False


def is_slash_command_injection(text: str) -> bool:
    """Check if text looks like a slash command template injection."""
    return bool(SLASH_COMMAND_PATTERN.match(text))


def is_injected_prompt(text: str) -> bool:
    """Check if text looks like a long injected prompt/template."""
    return len(text) > 500 and bool(INJECTED_PROMPT_PATTERN.match(text))


def is_agent_loop_prompt(text: str) -> bool:
    """Check if text is an agent loop / orchestrator prompt injection."""
    for pat in AGENT_LOOP_PATTERNS:
        if pat.search(text[:500]):  # Only check the beginning
            return True
    return False


# ---------------------------------------------------------------------------
# Lexical classification signals
# ---------------------------------------------------------------------------

# Correction patterns: negation + reference to what agent did, or explicit correction language
CORRECTION_PATTERNS = [
    re.compile(r"\b(?:no[,.]?\s+(?:that'?s|it'?s|I\s+(?:said|meant|want)))", re.IGNORECASE),
    re.compile(r"\b(?:that'?s\s+(?:wrong|incorrect|not\s+(?:right|what|how)))", re.IGNORECASE),
    re.compile(r"\b(?:don'?t\s+(?:do\s+that|use|remove|delete|change|touch|modify))", re.IGNORECASE),
    re.compile(r"\b(?:stop\s+(?:doing|removing|deleting|changing))", re.IGNORECASE),
    re.compile(r"\b(?:I\s+(?:said|meant|asked)\s+(?:to|for|not))", re.IGNORECASE),
    re.compile(r"\b(?:not\s+(?:that|those|this|like\s+that))\b", re.IGNORECASE),
    re.compile(r"\b(?:why\s+(?:did\s+you|are\s+you)\s+(?:remov|delet|chang|add|modif))", re.IGNORECASE),
    re.compile(r"\b(?:you\s+(?:broke|messed|screwed|ruined))", re.IGNORECASE),
    re.compile(r"\b(?:revert|undo|rollback|go\s+back)\b", re.IGNORECASE),
    # "fix the/this/that/it/your" but only at start of message or after period (not mid-sentence)
    re.compile(r"(?:^|\.\s+)(?:fix\s+(?:the|this|that|it|your))\b", re.IGNORECASE),
    re.compile(r"\b(?:actually|instead)\s*[,.]", re.IGNORECASE),
    re.compile(r"\bdisagree\b", re.IGNORECASE),
    re.compile(r"\bnope\b", re.IGNORECASE),
    # Sentence starting with "No." / "No," / "No " followed by correction/explanation
    # Exclude "No, I just misunderstood" which is an acknowledgment
    re.compile(r"^\s*No[.,!]\s+(?!I\s+(?:just\s+)?misunderstood|thanks|thank\s+you)\S", re.IGNORECASE),
    re.compile(r"\bthat'?s\s+not\s+(?:what|how|right)", re.IGNORECASE),
    # "you missed" / "you forgot" / "you skipped"
    re.compile(r"\byou\s+(?:missed|forgot|skipped|overlooked|ignored)", re.IGNORECASE),
]

APPROVAL_PATTERNS = [
    re.compile(r"^\s*(?:(?:looks?\s+)?good|great|perfect|nice|thanks|thank\s+you|lgtm|approved?|ship\s+it|go\s+ahead|yes|yep|yeah|ok(?:ay)?|sure|correct|right|exactly|sounds?\s+good)\s*[!.]*\s*$", re.IGNORECASE),
    re.compile(r"^\s*(?:fixed\s+it|all\s+good|that\s+works?|works?\s+for\s+me|push\??|merge)\s*[!.]*\s*$", re.IGNORECASE),
    re.compile(r"^\s*(?:keep\s+going|continue|go\s+on|proceed|please?\s+do)\s*[!?.]*\s*$", re.IGNORECASE),
    re.compile(r"^\s*(?:go\s+ahead)\b", re.IGNORECASE),
]

QUESTION_PATTERNS = [
    re.compile(r"\?\s*$"),  # Ends with question mark
    re.compile(r"^\s*(?:what|how|why|when|where|which|who|is|are|do|does|did|can|could|would|should|will|have|has)\s", re.IGNORECASE),
    re.compile(r"^\s*(?:tell\s+me|explain|describe)\s", re.IGNORECASE),
]

DIRECTIVE_PATTERNS = [
    re.compile(r"^\s*(?:please\s+)?(?:run|execute|build|test|deploy|push|commit|create|make|add|remove|delete|update|install|check|review|write|implement|refactor|fix|migrate|set\s+up|generate|find|show|look|help|try|use|move|copy|rename|clean|format|lint|send|put|get|fetch|pull|clone|branch|merge|perform)\b", re.IGNORECASE),
    re.compile(r"^\s*(?:can\s+you|could\s+you|would\s+you|should\s+we|I\s+(?:need|want)\s+(?:you\s+to|to)|we\s+(?:should|need|can|could))\s", re.IGNORECASE),
    re.compile(r"^\s*(?:have\s+@)", re.IGNORECASE),  # Multi-agent dispatch
    re.compile(r"^\s*(?:workflows?:)", re.IGNORECASE),  # Workflow commands
    re.compile(r"^\s*/\w+", re.IGNORECASE),  # Slash commands
    # "So, regarding" / "about the..." conversational directive/topic opener
    re.compile(r"^\s*(?:so,?\s+)?(?:regarding|about|for)\s+", re.IGNORECASE),
    # "Go ahead. Then..." - approval with continuation directive
    re.compile(r"^\s*(?:go\s+ahead|yes|ok|okay|sure)[.,!]?\s+(?:then|and|also|now|but|after)", re.IGNORECASE),
]


def score_correction(text: str) -> float:
    """Score how likely text is a correction (0.0 - 1.0).

    Real human corrections are short, conversational messages directed at the agent.
    Very long messages that incidentally contain correction-like words (e.g., agent
    loop prompts mentioning "fix" or "revert") should not score as corrections.
    """
    if not text.strip():
        return 0.0
    # Long messages are almost never corrections -- they are prompts or directives
    if len(text) > MAX_CORRECTION_TEXT_LENGTH:
        return 0.0
    matches = sum(1 for p in CORRECTION_PATTERNS if p.search(text))
    # Scale: 1 match = 0.6, 2+ = 0.8+
    if matches == 0:
        return 0.0
    score = min(0.6 + (matches - 1) * 0.15, 0.95)
    # Length penalty: corrections get less likely as messages get longer
    # A 500-char message is borderline; scale down gently
    if len(text) > 300:
        score *= max(0.5, 1.0 - (len(text) - 300) / 1400)
    return score


def score_approval(text: str) -> float:
    """Score how likely text is an approval (0.0 - 1.0)."""
    if not text.strip():
        return 0.0
    for p in APPROVAL_PATTERNS:
        if p.search(text):
            return 0.85
    return 0.0


def score_question(text: str) -> float:
    """Score how likely text is a question (0.0 - 1.0)."""
    if not text.strip():
        return 0.0
    matches = sum(1 for p in QUESTION_PATTERNS if p.search(text))
    if matches >= 2:
        return 0.8
    if matches == 1:
        # Question mark alone is strong but can be rhetorical
        if text.strip().endswith("?"):
            return 0.7
        return 0.5
    return 0.0


def score_directive(text: str) -> float:
    """Score how likely text is a directive (0.0 - 1.0)."""
    if not text.strip():
        return 0.0
    for p in DIRECTIVE_PATTERNS:
        if p.search(text):
            return 0.7
    return 0.0


# ---------------------------------------------------------------------------
# Main classifier
# ---------------------------------------------------------------------------

def classify_message(
    obj: dict,
    message_index: int,
    total_user_messages: int,
    session_type: str,
) -> tuple[str, float, dict]:
    """
    Classify a single user-role message.

    Returns: (label, confidence, signals_dict)
    """
    signals = {}

    # -----------------------------------------------------------------------
    # 1. Structural signals (highest priority)
    # -----------------------------------------------------------------------

    # Old-format toolResult (type=message, role=toolResult)
    if is_old_format_tool_result(obj):
        signals["old_format_tool_result"] = True
        return "system_message", 0.99, signals

    # Extract content
    msg = obj.get("message", {})
    content = msg.get("content", [])

    # New-format tool_result blocks in content
    if has_tool_result_blocks(content):
        signals["has_tool_result_blocks"] = True
        return "system_message", 0.99, signals

    if has_tool_use_id(content):
        signals["has_tool_use_id"] = True
        return "system_message", 0.98, signals

    # sourceToolAssistantUUID means this was generated by a tool, not a human
    if has_source_tool_uuid(obj):
        signals["source_tool_uuid"] = True
        return "system_message", 0.95, signals

    # -----------------------------------------------------------------------
    # 2. Extract text for lexical analysis
    # -----------------------------------------------------------------------
    text = extract_text_from_content(content)
    stripped = text.strip()

    # -----------------------------------------------------------------------
    # 3. Tag-based system message detection
    # -----------------------------------------------------------------------
    if has_system_tags(text):
        signals["has_system_tags"] = True
        return "system_message", 0.95, signals

    if has_system_prefix(text):
        signals["has_system_prefix"] = True
        # "[Request interrupted]" is a system notification
        if "[Request interrupted" in text:
            signals["request_interrupted"] = True
            return "system_message", 0.90, signals
        # "[Image:" is system-generated image reference
        if "[Image:" in text:
            signals["image_reference"] = True
            return "system_message", 0.85, signals
        return "system_message", 0.90, signals

    # Slash command template injections (long formatted prompts)
    if is_slash_command_injection(text):
        signals["slash_command_injection"] = True
        return "system_message", 0.90, signals

    if is_injected_prompt(text):
        signals["injected_prompt"] = True
        return "system_message", 0.85, signals

    # Agent loop / orchestrator prompt injections
    if is_agent_loop_prompt(text):
        signals["agent_loop_prompt"] = True
        return "system_message", 0.92, signals

    # -----------------------------------------------------------------------
    # 4. Empty or near-empty messages
    # -----------------------------------------------------------------------
    if len(stripped) == 0:
        signals["empty_message"] = True
        return "other", 0.90, signals

    if len(stripped) < 3:
        signals["very_short"] = True
        return "other", 0.70, signals

    # -----------------------------------------------------------------------
    # 5. Lexical classification (human messages)
    # -----------------------------------------------------------------------
    s_correction = score_correction(stripped)
    s_approval = score_approval(stripped)
    s_question = score_question(stripped)
    s_directive = score_directive(stripped)

    signals["score_correction"] = round(s_correction, 3)
    signals["score_approval"] = round(s_approval, 3)
    signals["score_question"] = round(s_question, 3)
    signals["score_directive"] = round(s_directive, 3)
    signals["text_length"] = len(stripped)

    # Position signal: first user message in a session is almost always a directive
    is_first = (message_index == 0)
    if is_first:
        signals["is_first_message"] = True

    # A correction that's also the first message is almost certainly a directive
    if is_first and s_correction > 0 and s_directive > 0:
        s_correction *= 0.3  # Heavily penalize correction for first message
        signals["first_msg_correction_penalty"] = True

    # For very short messages that match approval patterns, boost approval
    if len(stripped) < 50 and s_approval > 0:
        s_approval += 0.1
        signals["short_approval_boost"] = True

    # Corrections often reference the previous assistant action
    # Questions ending with ? but containing correction language = correction
    if s_correction > 0 and s_question > 0:
        # "Why did you remove..." is a correction, not a question
        if any(p.search(stripped) for p in CORRECTION_PATTERNS[6:8]):
            s_correction += 0.15
            s_question -= 0.2
            signals["correction_question_reclassify"] = True

    # Pick the highest-scoring category
    scores = {
        "human_correction": s_correction,
        "human_approval": s_approval,
        "human_question": s_question,
        "human_directive": s_directive,
    }

    best_label = max(scores, key=scores.get)
    best_score = scores[best_label]

    # If no pattern matched well, classify based on heuristics
    if best_score < 0.3:
        # Long messages (>200 chars) with no specific pattern = likely directive
        if len(stripped) > 200:
            signals["long_unmatched_as_directive"] = True
            return "human_directive", 0.50, signals
        # Short messages with no pattern = other
        signals["no_pattern_match"] = True
        return "other", 0.40, signals

    # If scores are close, reduce confidence
    sorted_scores = sorted(scores.values(), reverse=True)
    if len(sorted_scores) > 1 and sorted_scores[0] - sorted_scores[1] < 0.15:
        best_score *= 0.85
        signals["ambiguous_scores"] = True

    return best_label, round(min(best_score, 0.95), 3), signals


# ---------------------------------------------------------------------------
# Session processing
# ---------------------------------------------------------------------------

def parse_session(filepath: str) -> list[dict]:
    """Parse a JSONL session file and return all entries."""
    entries = []
    with open(filepath) as f:
        for line_idx, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                obj["_line_index"] = line_idx
                entries.append(obj)
            except json.JSONDecodeError:
                continue
    return entries


def extract_user_messages(entries: list[dict]) -> list[dict]:
    """
    Extract user-role messages from session entries.
    Handles both old format (type=message, role=user/toolResult)
    and new format (type=user).
    """
    user_msgs = []
    for entry in entries:
        etype = entry.get("type", "")
        # New format: top-level type=user
        if etype == "user":
            user_msgs.append(entry)
        # Old format: type=message with role=user or role=toolResult
        elif etype == "message":
            role = entry.get("message", {}).get("role", "")
            if role in ("user", "toolResult"):
                user_msgs.append(entry)
    return user_msgs


def extract_assistant_context(entries: list[dict], user_entry: dict) -> tuple[str, str]:
    """
    Extract the previous and next assistant message text for context.
    """
    line_idx = user_entry.get("_line_index", -1)
    prev_text = ""
    next_text = ""

    for entry in entries:
        eidx = entry.get("_line_index", -1)
        etype = entry.get("type", "")

        is_assistant = False
        if etype == "assistant":
            is_assistant = True
        elif etype == "message" and entry.get("message", {}).get("role") == "assistant":
            is_assistant = True

        if is_assistant:
            if eidx < line_idx:
                msg = entry.get("message", {})
                content = msg.get("content", [])
                prev_text = extract_assistant_text(content)
            elif eidx > line_idx and not next_text:
                msg = entry.get("message", {})
                content = msg.get("content", [])
                next_text = extract_assistant_text(content)
                break  # Only need the first one after

    return prev_text, next_text


def classify_session(filepath: str, session_type: str) -> list[ClassifiedMessage]:
    """
    Classify all user messages in a session file.

    Args:
        filepath: Path to JSONL session file
        session_type: "interactive" or "subagent"

    Returns:
        List of ClassifiedMessage objects
    """
    entries = parse_session(filepath)

    # Extract session ID from session entry or filename
    session_id = Path(filepath).stem
    for entry in entries:
        if entry.get("type") == "session":
            session_id = entry.get("id", session_id)
            break

    user_messages = extract_user_messages(entries)
    total_user = len(user_messages)

    # Count non-tool-result user messages for indexing human messages
    human_msg_index = 0
    results = []

    for msg_idx, user_entry in enumerate(user_messages):
        # Classify
        label, confidence, signals = classify_message(
            user_entry,
            message_index=msg_idx,
            total_user_messages=total_user,
            session_type=session_type,
        )

        # Extract text
        msg = user_entry.get("message", {})
        content = msg.get("content", [])
        raw_text = extract_text_from_content(content)

        # Get context
        prev_text, next_text = extract_assistant_context(entries, user_entry)

        result = ClassifiedMessage(
            session_id=session_id,
            session_type=session_type,
            message_index=msg_idx,
            line_index=user_entry.get("_line_index", -1),
            raw_text=raw_text[:2000],  # Truncate very long texts
            label=label,
            confidence=confidence,
            signals=signals,
            prev_assistant_text=prev_text,
            next_assistant_text=next_text,
        )
        results.append(result)

    return results


# ---------------------------------------------------------------------------
# Sampling
# ---------------------------------------------------------------------------

def sample_messages(
    corpus_dir: str,
    session_type: str,
    n: int = 500,
    seed: int = 42,
) -> list[ClassifiedMessage]:
    """
    Sample n user messages from sessions in corpus_dir.
    Stratifies across sessions to get diverse coverage.
    """
    session_dir = Path(corpus_dir)
    session_files = sorted(session_dir.glob("*.jsonl"))

    if not session_files:
        raise ValueError(f"No JSONL files found in {corpus_dir}")

    # First pass: collect all user messages with classifications
    all_messages = []
    for filepath in session_files:
        try:
            classified = classify_session(str(filepath), session_type)
            all_messages.extend(classified)
        except Exception as e:
            print(f"Warning: failed to process {filepath}: {e}", file=sys.stderr)

    if len(all_messages) <= n:
        return all_messages

    # Stratified sample: ensure we get messages from many sessions
    # and a mix of labels
    rng = random.Random(seed)

    # Group by session
    by_session = {}
    for msg in all_messages:
        by_session.setdefault(msg.session_id, []).append(msg)

    # Sample proportionally from each session
    session_ids = list(by_session.keys())
    rng.shuffle(session_ids)

    # Allocate samples per session proportionally
    total = len(all_messages)
    sampled = []
    remaining = n

    for sid in session_ids:
        session_msgs = by_session[sid]
        # Proportional allocation with minimum of 1
        alloc = max(1, round(len(session_msgs) / total * n))
        alloc = min(alloc, remaining, len(session_msgs))
        if alloc > 0:
            sampled.extend(rng.sample(session_msgs, alloc))
            remaining -= alloc
        if remaining <= 0:
            break

    # If we still need more, sample from remaining
    if len(sampled) < n:
        already = {(m.session_id, m.line_index) for m in sampled}
        pool = [m for m in all_messages if (m.session_id, m.line_index) not in already]
        rng.shuffle(pool)
        sampled.extend(pool[: n - len(sampled)])

    return sampled[:n]


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def select_validation_sample(
    messages: list[ClassifiedMessage],
    n: int = 50,
    seed: int = 123,
) -> list[ClassifiedMessage]:
    """Select n messages for manual validation, stratified by label."""
    rng = random.Random(seed)
    by_label = {}
    for msg in messages:
        by_label.setdefault(msg.label, []).append(msg)

    # Try to get at least 2 from each label
    selected = []
    for label, msgs in by_label.items():
        take = min(2, len(msgs))
        selected.extend(rng.sample(msgs, take))

    # Fill remainder randomly
    remaining = n - len(selected)
    if remaining > 0:
        already = {(m.session_id, m.line_index) for m in selected}
        pool = [m for m in messages if (m.session_id, m.line_index) not in already]
        rng.shuffle(pool)
        selected.extend(pool[:remaining])

    return selected[:n]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Classify user messages in Claude Code session transcripts"
    )
    subparsers = parser.add_subparsers(dest="command")

    # classify: classify a single session file
    classify_parser = subparsers.add_parser("classify", help="Classify messages in a session file")
    classify_parser.add_argument("filepath", help="Path to JSONL session file")
    classify_parser.add_argument(
        "--session-type", choices=["interactive", "subagent"], default="interactive",
        help="Session type (default: interactive)"
    )
    classify_parser.add_argument("--json", action="store_true", help="Output as JSON")

    # sample: sample and classify from corpus
    sample_parser = subparsers.add_parser("sample", help="Sample and classify from corpus")
    sample_parser.add_argument("--interactive-dir", required=True, help="Interactive sessions directory")
    sample_parser.add_argument("--subagent-dir", required=True, help="Subagent sessions directory")
    sample_parser.add_argument("--n", type=int, default=500, help="Samples per session type")
    sample_parser.add_argument("--output", required=True, help="Output JSON file path")
    sample_parser.add_argument("--seed", type=int, default=42, help="Random seed")

    # validate: generate validation sample
    validate_parser = subparsers.add_parser("validate", help="Generate validation sample")
    validate_parser.add_argument("--labeled-file", required=True, help="Labeled messages JSON file")
    validate_parser.add_argument("--n-interactive", type=int, default=50)
    validate_parser.add_argument("--n-subagent", type=int, default=50)
    validate_parser.add_argument("--output", required=True, help="Output validation file")

    # stats: print classification statistics
    stats_parser = subparsers.add_parser("stats", help="Print classification statistics")
    stats_parser.add_argument("labeled_file", help="Labeled messages JSON file")

    args = parser.parse_args()

    if args.command == "classify":
        results = classify_session(args.filepath, args.session_type)
        if args.json:
            print(json.dumps([r.to_dict() for r in results], indent=2))
        else:
            for r in results:
                print(f"[{r.label:20s}] (conf={r.confidence:.2f}) {r.raw_text[:120]}")

    elif args.command == "sample":
        print(f"Sampling {args.n} messages from interactive sessions...")
        interactive = sample_messages(args.interactive_dir, "interactive", args.n, args.seed)
        print(f"  Got {len(interactive)} interactive messages")

        print(f"Sampling {args.n} messages from subagent sessions...")
        subagent = sample_messages(args.subagent_dir, "subagent", args.n, args.seed)
        print(f"  Got {len(subagent)} subagent messages")

        all_messages = [m.to_dict() for m in interactive + subagent]
        os.makedirs(os.path.dirname(args.output), exist_ok=True)
        with open(args.output, "w") as f:
            json.dump(all_messages, f, indent=2)
        print(f"Saved {len(all_messages)} labeled messages to {args.output}")

        # Print stats
        from collections import Counter
        print("\n=== Interactive ===")
        counts = Counter(m.label for m in interactive)
        for label, count in sorted(counts.items()):
            print(f"  {label:20s}: {count:5d} ({count/len(interactive)*100:5.1f}%)")

        print("\n=== Subagent ===")
        counts = Counter(m.label for m in subagent)
        for label, count in sorted(counts.items()):
            print(f"  {label:20s}: {count:5d} ({count/len(subagent)*100:5.1f}%)")

    elif args.command == "validate":
        with open(args.labeled_file) as f:
            data = json.load(f)

        interactive = [ClassifiedMessage(**d) for d in data if d["session_type"] == "interactive"]
        subagent = [ClassifiedMessage(**d) for d in data if d["session_type"] == "subagent"]

        val_interactive = select_validation_sample(interactive, args.n_interactive)
        val_subagent = select_validation_sample(subagent, args.n_subagent)

        validation = [m.to_dict() for m in val_interactive + val_subagent]
        os.makedirs(os.path.dirname(args.output), exist_ok=True)
        with open(args.output, "w") as f:
            json.dump(validation, f, indent=2)
        print(f"Saved {len(validation)} validation samples to {args.output}")

    elif args.command == "stats":
        with open(args.labeled_file) as f:
            data = json.load(f)

        from collections import Counter

        for stype in ["interactive", "subagent"]:
            msgs = [d for d in data if d["session_type"] == stype]
            counts = Counter(d["label"] for d in msgs)
            print(f"\n=== {stype} ({len(msgs)} messages) ===")
            for label, count in sorted(counts.items()):
                avg_conf = sum(d["confidence"] for d in msgs if d["label"] == label) / max(count, 1)
                print(f"  {label:20s}: {count:5d} ({count/max(len(msgs),1)*100:5.1f}%) avg_conf={avg_conf:.3f}")

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
